language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: ipYEMFy1O1mAd299FO7FM5kpxlc97SQ3x2GAD8AHt1sj2HlGoG7hcfTJzO+Juvv6Smzissa32fs8YG6V6d++OqTnjvQmYnQ51sfDZpy4HguEg4CKPBIm8RpmGUWV3Y6K0LqvijIKa/EiMRyo3k3i7ZBV7WaOOjCM4chxB7h8sw1hL2qpdR4IuAWoU7/3LzjTNo4ondV8wLupwKkP1Zh0y1KiG6E/PMTaA8BAKbN5JXN+nZcOJ3lIaMSu90TNIJ/LdIlM7Qn68ht1JSPT5klZqMrbt0LJ5+YHam+HO+LMdCNM4FKCMIbZYIgIt6yb3FoOZT7piHcJUkZTC5NbzQ/i7GqlBH6MyF/FpM6GRd9DNNECt5kJLT14Vj03rNWi9xTXDdx2CCutX8zwR0BlNn6bA3opmr4Kg4XjmS7Z8LH88ztxEvzFYJCjudpBft7hwkt8m2mJFIuyAyNsRUkLMbtaZD4+7wo+RxFix0wGqcnJmb+P1Gv+AFF28q7f/9c4eHs1X31ehhwx7DGMWH6rIrE+7hZOwsRCVmQXvhAVf7aaENjLRwhWaYAC6zFMAo29BPklXCSTxzxS/NS6allnc5aA6FIyLWn8fPyAlAYN/fyy0LfON98N6JZm92p+OiLYh8bYNiF2nrFIX7ICSKo2SDJweQ4qhauHutD5SrJYtfVCNWk=
  - secure: FxWbGhn4cTM/4eXw5UqZWXmJZn2+lxBOZwKr1aU+E7A4DHwEITEyKyZgCfVWzVU6FtxJxXZFwwB+TLvEcXP+lJQEeBOSyv6WwVYqLKIUol1ytNFpBZsTOJYeWiFu9NWGsa6o9Q7tcd39vJoopewp0HBx2BNojmlL4SZG8KQEsIwRpIk8TEUwyFnLK1JofIBwYf/FyxFMYZ3pZnW4w4h9/tszCI6L/9d9U/pNV0DNSFLu/s4+dyV8i2qoNk2YMmZk3igdMjglxAEvY2M4PiqzKvNhN7jgoDF8GkkNrXM+XfFaJy/nNJhx4P6ifIjywqwizv5BzCyh2bguon3hjja52R7S0BezPUtKqoRlDASkuD14LzD0KBOmZ/X7SFpd5WNFbsHsV/j/nExIhW47LZChb2TZRATF1vjSRHlqzXXmQ0ezyP5Jf6OOy8vd1jiVjivwqspzvQciGpmH2sAh5PnA4R5H5ML6LuaeKHaWETxfkJInNHSitX9TLMsHr2s/sj37sWBfZAk1tDwE6GBX7r3iHZPmHzUeQm+uDtghav2229VnWrxv2wMYM+//sp/BvS09Zmf2TvSbEeP6Q217Y5qdsmI3iNZ1YU4ArzAz2DqmIhxt3tl1ZXPRLxcXmpgnfH2b4KnI1716LNwTn7Ln1y/MKrBQ56E+OpRunkFw1g7IzUk=
