language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: nr5DdpQUyQyLDKnu7Vm+SLzbELnFoIFqdMw8D0yG3j9NpMy0Zn0YHM7idxkJz5pMbb3l4T02Ju04OVou7OLU9g7mAZiRgnRGRsbTb4NL70fOFJQWs3f1kG73yqXe30hpRJvqf1ujUCiI527mWU95yrKYP6rkjDVmi7uQmMfcOkuZSxrJeOIP4FgHGg/6X/JmJOgQMWovBVMoBpg2+3eiobLBHqiTASgtmNGJrabJzfC/9fn8yz2c/NfBOwkeUPXppILQsO0mQmI8sqUJMBniVFrTMo8zYTYkGCiN9pg59TfqfFzppqVP5v6Xe1bzhLxYZAlNrvUEvwJu+BGPrjIe2B8MZRpGyKsqzpJbEVzM2g31q8+Z4JxWg/WeUkj3wusVRICy3lKn0C6DLy0PCHrCSw/kXSzQDJ1jsUMmCAi9OKxgvN0XcohtaPqrbMIOHzlOld481x6eC0/lgSH2EQ9zAqUn4ES3SofKSr3JGSQ4Kh1dnXhMELFAG6k3yeQ3wfIvGUDhqflLWrXwhXd9V5YIwMlPBok0kLekYn80bP988L4WMpzE0aYFGKOkyoP1m6Hm7o6Mm1AZlfLI6xCNNrD48JVVabteNDbhfiovN4R6twIH9Xw9kvQrlIIvUOHWoDsaM2ww9NMXZaM3X/GZnfb+WS1cYNeDm4rkRDExdb2eo2s=
  - secure: NEzO6X30LjtVFE45+4KfI+1jY2c0piU4PVnz0zEv6tth0g4w05qaFFQSVo5e3IIdgzB0J0L1iXOJeSLHxyg/OnEgKL/G0bBDamk73SCEoTKAVPADPe8T5sx0Fpq1E7XZOKW+mO0N4tCF/Q1abreCvG0Z2P+IUf6cewEqFdqZpITJsrJGZW6uAg8ZoVgN5AYdDuVWreBie2svvrWn8WUhbZH/bIJfCJIC7Rhj202uGl5bZHpQojq2IHAaTHDkiZuvHOabRjJj96rycAB7ROFqc/FPSilz4TQSVQX/5Vdu6CL5YG/Gmzz4mtqk/MHtTyTDdFPG16EcH8hWvtCM4xC4NVW0HvuCBcHWiDU66cge3l5VGwinwEsk4jLfOhPvNtvV4s33QXVd1eQ/NtRmEBuzjjeImUP20S1Nmxh071EIzAYHhJ4AiRGyR5XQ0PXNrhtQzRc7Xl89Sc+/lr5Hp269S5RYJUHg1BaPWmADcct+8E6HKrLcUuQDSTCAYDNQPwhpo+Dt5/Qtz3uYdbrpoJdYG976PCU1RZnmiY2hE2BcvEyxr+EpCAKeA+q2HmgAlrdPEY5q213UPXB5jG3MHTd2T2yvmHxqK9b+ssRwVKwvoZgZAe5B3hPURQiLeP2iAPy6kX+LVziw/BvXWhX9aX8zD8rT0sQt7xD26BGbIqbESYU=
