language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: aSYsPW8hIwktH3xQGDgyCdFNxtvXGQRjk+K/02/wDpb4YHugOpmvFdiP0/Of6CT2AdGNmod1j+4HsHFDxclEIqc1q1kDeoEage/Xdp+QAVj1Ye7uYbzEK3uISsslI81OqmS8IqoCljYJhQ6CBnqGW1c2fmnOGa7DiQ1w1V/9k0/vsqfwZZDogw2uG/T+xZEqJomYY30I2oq3m1OkjJrtm4ZQTXLHs+MppSY1pLERr9QfBj1ELwmJtdTp3/58Gzpa99z4ZFOuGd1/lfLHo5457ZVluSWza3+6J3E52AoIIwllCGEBR+NB3k6j/gQatL5gNyksWgJLZYOGIvvbhrDpBuFBO09C1OJ+Brd28Y5YzSahPsGrPrBLaFYN/5tGR1MIDUsRwDGGEwA2yNDqQ0cVkBW/R4Gw21cV+S1/8GDw7gr0SXg2dGMnc1koZrMjM69g/0Zy+m6rRaAEpJcMglnZGsU99Na0SxShToRdcxyZJFKUkuRHNs/NIncdOIhG4t1o1NYym8qinr6oT16iGwx/deMsUVcvzy6Ms6HWe9fwASo8XoWRVpWnq+oYNR8UJE8eOwAJc4f/9AIw91rjK3zsLeb4vGUkqs9DO9W7vzsX1GWjZ+FuCht8ILFX0K1TDUWG1ktlpTqx2u+Mz+CrFqZI1FmOSzJCCdkDDwRd8klm/2A=
  - secure: BTpzX9ckmUArUzadZM+W0okgyEVmEPUL0kQTvc0gMYsAHgkXRwTYJLhco+P9/5LOjewBrC3yFI4Mnlujh7N5ZO7q3gBuecsSaDgOl0An7sXo1voWMTER0ctEKjiCBkuV4sS60pnLrd7o9oK8iIalfRAZfAYDJpEGfOk3WW3IqV0CBYf7QZlfQmzkhK+Lbc5aSRJ74oELxXXY3v4wFOyQPRoOtJ0Iq2VG5P7Lys/xnocL8vyCLS8WaeA8vE/nmFcJ4dlk02vfHW7EQAx3fwvF2YowpOMWQQBQQr13jPDU6h4X1/CCxKlBorgFSXDYZNpXevMv6drYLe7KfYbzqTZBAgnZAZKulNOPUb7Ux9QRJtFKbgaJoicDZaPyPMhjPnvCS40a9pgNM3l2Ej2a7D+25/eFzvQNj+4iQPOgpyq0O8BTlj5sEZOlsGVsAroJtGtzNGHvWS7+3POSS/BuR4jexyp9kCZznNaXWtds8mSspYeu1rgp8lakYe/MImcZcGsJsBtTI+3tn/ScL5Dag0He09v3BN4iEWNl/VSjWzGKKbOeT8jepeTW3sg0yJi/xyx7Nowgy88I+uIwVfv0x2w+sM1DFEWslOhZspCkXC7KetY0NRVtbxLIfW/4rLfvyGLjzQHdw+/jQt2LcBubQkdIvsPHdgyVHesDBQUGksR9C6Q=
